export const detalleProductos = [
    
    {   id: 1, 
        title: 'Game of Thrones' , 
        author: 'George R.R Martin',
        description:'La exitosa serie de HBO A GAME OF THRONES está basada en la exitosa serie internacional de George R R Martin A SONG OF ICE AND FIRE, la mayor epopeya de fantasía de la era moderna. JUEGO DE TRONOS es el primer volumen de la serie.', 
        price: '$3000', 
        pictureUrl: "https://imagessl6.casadellibro.com/a/l/t5/36/9780007448036.jpg",
    },
    {   id: 2, 
        title: 'Harry Potter y la piedra filosofal', 
        author: 'J.K Rowling', 
        description: 'Harry Potter y la piedra filosofal es el primer volumen de la ya clásica serie de novelas fantásticas de la autora británica J.K. Rowling.', 
        price: '$2700', 
        pictureUrl: "https://imagessl8.casadellibro.com/a/l/t5/18/9788498386318.jpg",
    },
    {   id: 3, 
        title: 'El camino de los Reyes', 
        author: 'Brandon Sanderson', 
        description: 'El camino de los reyes es el primer volumen de «El Archivo de las Tormentas», el resultado de más de una década de construcción y escritura de universos, convertido en una obra maestra de la fantasía contemporánea en diez volúmenes. Con ella, Brandon Sanderson se postula como el autor del género que más lectores está ganando en todo el mundo.', 
        price: '$2600', 
        pictureUrl: "https://imagessl1.casadellibro.com/a/l/t5/41/9788413143941.jpg",
    },
    {   id: 4, 
        title: 'Galant', 
        author: 'V.E. SCHWAB', 
        description: 'TODO PROYECTA UNA SOMBRA. INCLUSO EL MUNDO EN EL QUE VIVIMOS. Y COMO OCURRE CON TODA SOMBRA, HAY UN LUGAR DONDE ESTA SE UNE CON LO QUE LA GENERA.', 
        price: '$2400', 
        pictureUrl: "https://imagessl4.casadellibro.com/a/l/t5/64/9788416517664.jpg",
    }
]